(in-package :com.sympoiesis.champ)

(defparameter *vector-of-symbols*
  (let ((syms nil))
    (do-external-symbols (sym :cl)
      (push sym syms))
    (subseq (coerce syms 'vector) 0 256)))

(defun test-champ-maps (n-iterations)
  (declare (optimize (debug 3)))
  (macrolet ((test (form)
	       `(unless ,form
		  (error "Test failed: ~S" ',form))))
    (dotimes (i n-iterations)
      (when (= 9 (mod i 10))
	(format t "."))
      (let ((tbl (make-table (if (logbitp i 1) #'sxhash #'int-torture-hash) #'eql))
	    (clht (make-hash-table)))
	(dotimes (j 256)
	  (let ((key (if (logbitp i 1)
			 (svref *vector-of-symbols* (random (length *vector-of-symbols*)))
		       (random 128)))
		(value (random 65536)))
	    (test (eql (table-get tbl key) (gethash key clht)))
	    (if (< (random 100) 30)
		(progn
		  (table-remove tbl key)
		  (table-verify tbl)
		  (remhash key clht)
		  (multiple-value-bind (val found?)
		      (table-get tbl key)
		    (declare (ignore val))
		    (test (not found?))))
	      (progn
		(table-put tbl key value)
		(table-verify tbl)
		(setf (gethash key clht) value)
		(multiple-value-bind (val found?)
		    (table-get tbl key)
		  (test (and found? (eql val value))))))))
	(test (= (table-size tbl) (hash-table-count clht)))
	(if (logbitp i 2)
	    (do-table (k v tbl)
	      (test (eql v (gethash k clht)))
	      (remhash k clht))
	  (do ((iter (make-table-iterator tbl)))
	      ((funcall iter ':done?))
	    (multiple-value-bind (k v)
		(funcall iter ':get)
	      (test (eql v (gethash k clht)))
	      (remhash k clht))))
	(test (zerop (hash-table-count clht))))))
  t)

;;; Hash function for testing only.
(defun int-torture-hash (x)
  ;; Drop the two low-order bits to force collisions, and spread the bits out to force more levels
  ;; to be created.  Also, values equal mod 1024 will have the same hash.
  (let ((val (ash x -2)))
    (dpb (ldb (byte 2 6) val)
	 (byte 2 15)
	 (dpb (ldb (byte 2 4) val)
	      (byte 2 10)
	      (dpb (ldb (byte 2 2) val)
		   (byte 2 5)
		   (ldb (byte 2 0) val))))))

(defun map-verify (map)
  (declare (type champ-map map))
  (map-tree-verify (champ-map-contents map) (champ-map-hash-fn map)))

(defun table-verify (table)
  (declare (type champ-table table))
  (map-tree-verify (champ-table-contents table) (champ-table-hash-fn table)))
